name: GuardedEdit
version: ${project.version}
main: ru.lazytechwork.guardededit.GuardedEdit
api-version: 1.13
depend: [WorldEdit, WorldGuard]
authors: [LazyTechwork]
description: Prevent players from WorldEdit in guarded regions
